title: Course Website
description: website to host resources for courses
theme: just-the-docs

url: https://sunil-dhaka.github.io/course

aux_links:
  Template Repository: https://github.com/sunil-dhaka/course
